---
additional:
- temp

files:
- '!Dockerfile'
- '!README.md'
- '!.gitignore'
- '!.pre-commit-config.yaml'
- '!.yamllint'
- '!.secrets.baseline'
- '!.github/pull.yml'
- '!.github/dependabot.yml'
- '!.github/template-sync.yml'
- '!.github/workflows/pre-commit-update.yml'
